name: Snake Animation
on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: 'Sahhhiiillllll'
          outputs: |
            github-contribution-grid-snake.svg:
              # default options
          # The action will generate the SVG and commit to the current branch
